/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class StockLibTest {
    @Test public void importantMethodReturnsTrue() {
        StockLib classUnderTest = new StockLib();
        assertTrue(classUnderTest.importantMethod(), "importantMethod should return 'true'");
    }
}
